# This compose file is meant for development purposes.
# Please use the deployment steps provided in the readme for production use.

services:
  badgetrack:
    build: .
    ports:
      - "8925:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
